# Eureka configuration
# Indicando que essa aplicação não precisa se registrar num Servidor Eureka, pois, é ela mesmo
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

# Server configuration
server:
  port: 8761